### ISSUE TITLE
Reporter:  workup histograms, for Phil

### ISSUE THREAD

**Issue by nsfabina** [pgbrodrick/bfg-nets#63]
Per conversation:
- need better guidance on histogram plots
- legend
- constant y-axis across plots
- differentiate bins for zero from non-zero bins
- misc improvements as they come up

**Comment by nsfabina** [comment]
also, note that there's likely an indexing error if num responses exceeds num per page and it spills onto a second page

**Comment by nsfabina** [comment]
also, maybe rename the function to something like plot_sample_histograms (as part of a broader effort to shorten and clarify names, I had been being too verbose and specific, to the point where it made things less clear)

**Comment by pgbrodrick** [comment]
Progress here...Y axis corrected, legend added.  Still need more info and binning consistency.  I believe the indexing error is now handled but need to double check.

**Comment by pgbrodrick** [comment]
Fixed a variety of issues here, made visualizations look better, renamed function, added outlier support.  I'm not seeing the bug anymore...please reopen if you see it again!
